### PR TITLE
nvdash: reset colorcolum

### PR DESCRIPTION
**Pull request by robbash**

### CODE REVIEW

**Comment by robbash** [comment]
Hey @siduck. I'm using `colorcolumn` when coding but thought it might be worth resetting in `nvdash`. Cheers

**Review by siduck — APPROVED** [review]

**Comment by siduck** [comment]
hi @robbash could you show images with/without your change?

**Comment by robbash** [comment]
@siduck sure. 

set-colorcolumn

This is for a textwidth of 80 and using colorcolum = +1. Left window is without the setting applied, right one is with the setting.

**Comment by siduck** [comment]
@robbash  I'm sure you'd see the line for nvcheatsheet too! can you submit another PR for nvcheatsheet's grid/simple.lua files? :)

**Pull request merged**
