### PR TITLE
Implementation of custom separators

### PR DESCRIPTION
**Pull request by Ethanol48**
Add the ability to create and override separators

### CODE REVIEW

**Comment by Ethanol48** [comment]
### Changes

This change introduces a simple function that combines two tables, the default_separators and custom separators found in the override files in the custom folder.

I made this change for better flexibility, I like to make my own fonts with custom symbols for UI.

And I thought that some people would appreciate it, instead of overriding the entirety of the status line, people could change the separators.

**Comment by Ethanol48** [comment]
I made it with the v2.0 version of the plugin, but, as of right now it can be easily integrated in v3.0 .

**Comment by siduck** [comment]
image

there's already an option for it btw

**Comment by Ethanol48** [comment]
Ohh I didn't see that, I was with the idea of being able to have multiple separators if you would want to change it

**Pull request closed without merging**
