### PR TITLE
Fix statusline withing laststatus=2

### PR DESCRIPTION
**Pull request by ein-shved**
In multi-window mode we need to behave differ in different windows according to g:statusline_winid variable set by nvim

### CODE REVIEW

**Comment by siduck** [comment]
vim.g.statusline_winid always returns nil for me.

Also you forgot vscode  , vscode_colored statuslines

**Comment by ein-shved** [comment]
@siduck I've guided with [this](https://neovim.io/doc/user/options.html#g%3Astatusline_winid). Did you try `:set laststatus=2`?

Will update for vscode too soon. There is many copypastes there. Have you thought about refactoring?

**Comment by ein-shved** [comment]
@siduck  Updated for vscode and fix formatting

**Comment by siduck** [comment]
@ein-shved  
image

will test the PR this weekend

**Comment by lucario387** [comment]
Looks good

**Pull request merged**
