### PR TITLE
Fix Issue #250

### LINKED ISSUE #250: Opening neovim in / directory causes the status line to error.
**Describe the issue**
Due to the way the `cwd` module of the statusline is generated. It produces an error when neovim is opened in the `/` directory.

```lua
M.cwd = function()
  local icon = "%#St_cwd_icon#" .. "󰉋 "
  local name = "%#St_cwd_text#" .. " " .. vim.loop.cwd():match "([^/\\]+)[/\\]*$" .. " "
  return (vim.o.columns > 85 and ("%#St_cwd_sep#" .. sep_l .. icon .. name)) or ""
end
```

I'm guessing the match statement cannot handle the directory just being `/` and it errors out.

I have already looked to see if the issue has been reported and it was for v2.0: https://github.com/NvChad/ui/issues/197

I have updated all my plugins to see if maybe I had an older version, but it still happens.

**To reproduce**
```
cd /
nvim
```

**Expected Behaviour**
No error.

**Screenshots**
imatge

**Desktop**

- Operating System: ArchLinux
- Terminal: alacritty
- Version of Neovim: v0.9.5

### PR DESCRIPTION
**Pull request by David-Aguilo**
Fixes https://github.com/NvChad/ui/issues/250 where the statusline will error when opening it in the `/` directory.

### CODE REVIEW

**Comment by siduck** [comment]
`vim.loop.cwd():match "([^/\\]+) or vim.loop.cwd()`

**Comment by David-Aguilo** [comment]
Like this?
```lua
M.cwd = function()
  local icon = "%#St_cwd_icon#" .. "󰉋 "
  local name = "%#St_cwd_text#" .. " " .. vim.loop.cwd():match "([^/\\]+)" or vim.loop.cwd() .. " "
  return (vim.o.columns > 85 and ("%#St_cwd_sep#" .. sep_l .. icon .. name)) or ""
end
```
Still generates an error.
imatge

**Comment by siduck** [comment]
```lua
local cwd = vim.loop.cwd()
(cwd:match "([^/\\]+)" or cwd)
```

**Comment by David-Aguilo** [comment]
Implemented as
```lua
M.cwd = function()
  local icon = "%#St_cwd_icon#" .. "󰉋 "
  local cwd = vim.loop.cwd()
  local name = "%#St_cwd_text#" .. " " .. (cwd:match "([^/\\]+)" or cwd) .. " "
  return (vim.o.columns > 85 and ("%#St_cwd_sep#" .. sep_l .. icon .. name)) or ""
end
```
Now it shows `/` when in the `/` directory, however when inside of subdirectories with depth greater than 1, it will show the depth 1 directory. For example, when opening nvim in `/root/iced/examples/editor` (I'm in root because I am making the tests inside of docker), it shows `root` as the working directory:
imatge
In the image I have ran `:pwd` nvim command to show the directory I am in.

**Comment by siduck** [comment]
my bad, its `:match "([^/\\]+)[/\\]*$"`

**Comment by David-Aguilo** [comment]
Done, force pushed the branch to replace the previous commit

**Review by siduck — APPROVED** [review]

**Pull request merged**
