### PR TITLE
Fix for current terminal buffer closing when closing other buffer

### PR DESCRIPTION
**Pull request by adamallaf**
Related to https://github.com/NvChad/ui/issues/319

### CODE REVIEW

**Comment by siduck** [comment]
@adamallaf  try the code i committed to your branch!

**Comment by adamallaf** [comment]
> @adamallaf try the code i committed to your branch!

Nope, this won't fix the issue because `bufnr = 1` is the number of the buffer I clicked X for, while `cur_buf()` returns the current buffer's number.

So `bufnr = bufnr or cur_buf()` does not do anything because in the if condition there is no validation for the for terminal's buffer number.

**Comment by adamallaf** [comment]
> @adamallaf try the code i committed to your branch!

ohh, Ok, that works.

**Review by siduck — APPROVED** [review]

**Comment by adamallaf** [comment]
Thanks!

**Pull request merged**
