### PR TITLE
fix(themes): add missing themes

### PR DESCRIPTION
**Pull request by davimmt**
image

### CODE REVIEW

**Comment by davimmt** [comment]
Related to [this theme](https://github.com/NvChad/base46/blob/v2.5/lua/base46/themes/chadracula-evondev.lua).

**Comment by siduck** [comment]
@davimmt  i think it'll be better for us to automate this part! like a github workflow which will update types on push.

cuz more themes need to be added https://nvchad.com/news/v2.5_release#new_themes

but themes are located in base46 repo! 

so i think the automation must be added in base46  repo and it'll push to this UI repo's nvchad_types dir

**Comment by siduck** [comment]
so i wont merge this yet. same thing needs to be done with the highlight groups

**Comment by lucario387** [comment]
Just run the generator for that :)

**Comment by davimmt** [comment]
Agreed. Opened to raise awareness, at minimum.

**Comment by siduck** [comment]
> Just run the generator for that :)

this?

https://github.com/NvChad/ui/blob/v2.5/scripts/update-nvchad-types.lua 

So this must be done when staying in nvim itself right?

**Comment by lucario387** [comment]
or `nvim -l scripts/update-nvchad-types.lua`

**Comment by KorigamiK** [comment]
> or `nvim -l scripts/update-nvchad-types.lua`

Hey, can you confirm this command works on your machine? because on mine it errors out:

```sh
$ nvim -l scripts/update-nvchad-types.lua        
E5113: Error while calling lua chunk: scripts/update-nvchad-types.lua:5: module 'base46' not found:
	no field package.preload['base46']
	no file './base46.lua'
	no file '/usr/share/luajit-2.1/base46.lua'
	no file '/usr/local/share/lua/5.1/base46.lua'
	no file '/usr/local/share/lua/5.1/base46/init.lua'
	no file '/usr/share/lua/5.1/base46.lua'
	no file '/usr/share/lua/5.1/base46/init.lua'
	no file './base46.so'
	no file '/usr/local/lib/lua/5.1/base46.so'
	no file '/usr/lib/lua/5.1/base46.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	[C]: in function 'require'
	scripts/update-nvchad-types.lua:5: in main chunk
```

But the require error goes away if I do it from within with `:luafile` :thinking:

**Comment by lucario387** [comment]
because base46 is not loaded on startup.

**Comment by siduck** [comment]
@KorigamiK what about opening nvim and just running `:lua filepath...`

**Comment by KorigamiK** [comment]
> because base46 is not loaded on startup.
I added this to my config:
```lua
  {
    "NvChad/base46",
    lazy = false,
  },
```
image

And yet, I get the same error.

**Comment by siduck** [comment]
@KorigamiK yea didnt work. can you just open nvim and run `:luafile   filepath` 
that worked for me

**Comment by siduck** [comment]
that worked for me

**Comment by KorigamiK** [comment]
@siduck That's true, I was trying to do this in the command line so I can add this generator to the CI for the repo

**Comment by lucario387** [comment]
Forgot im running it from a different version :D 
But the gists is that base46 is not found in rtp during nvim -l unless you set it beforehand

I think the script should be reworked to be CI-only

**Comment by siduck** [comment]
i no longer face that issue, its fixed

**Pull request closed without merging**
