### PR TITLE
feat: remove unnecessary whitespace

### PR DESCRIPTION
**Pull request by 89iuv**
This PR is intended to remove the un necessary white space so that the formatting is more consistent and less space is used.

### CODE REVIEW

**Review by siduck — APPROVED** [review]

**Review by siduck — APPROVED** [review]

**Comment by siduck** [comment]
your change looks like this on my terminal

image

**Comment by 89iuv** [comment]
I think it is a problem with the way the terminal renders the font. 

On my end i have:
image

Where you can see that there is a double space between the icon and the LSP text.

On github diff you can see the same thing:
image

I am using iterm2.

**Comment by siduck** [comment]
try using non mono font for iterm2

**Comment by 89iuv** [comment]
Using non mono font makes it look ok:
image

There is still a difference in space between the yellow triangle and the number as compared to the other lsp diagnostic metrics on the status bar.

Should i reopent this PR: https://github.com/NvChad/ui/pull/258

**Comment by siduck** [comment]
image

on my terminal with your change

**Comment by siduck** [comment]
*cod icons look well but they're outlined

image

**Comment by 89iuv** [comment]
From my point of view it looks better with just one space between the "triangle" and the "number". Even if it feels like the "triangle" and number are closer than the rest, they are not.

Without changes:
image

**Comment by siduck** [comment]
hmm you i'll merge the other pr then

**Review by siduck — APPROVED** [review]

**Pull request merged**
