### PR TITLE
feat(tabufline)!: add `TbufPick` command

### PR DESCRIPTION
**Pull request by tomasky**
just like bufferline.nvim  `BufferLinePick` command ,some functions refer to it

### CODE REVIEW

**Comment by tomasky** [comment]
need to map  `["<leader>x"] `  to `Tbufclose`

**Comment by siduck** [comment]
i think this feature seems bloated, what if there are two  files of same name? like `custom/init.lua` and `nvim/init.lua`

**Comment by tomasky** [comment]
yes , like custom/init.lua and nvim/init.lua, you can switch  to `tomasky/nvchad-ui`  and   see what it looks like

**Comment by tomasky** [comment]
yes , like custom/init.lua and nvim/init.lua, you can switch  to `tomasky/nvchad-ui`  and   see what it looks like

**Comment by siduck** [comment]
ok this works but we have to run tbufpick then the letter, wouldnt it be nice to just have numbers to switch buffers?

like : 

press 3 to go to 3rd buffer

**Comment by tomasky** [comment]
> ok this works but we have to run tbufpick then the letter, wouldnt it be nice to just have numbers to switch buffers?
> 
> like :
> 
> press 3 to go to 3rd buffer

no , That's a lot of keys to map

**Comment by siduck** [comment]
> > ok this works but we have to run tbufpick then the letter, wouldnt it be nice to just have numbers to switch buffers?
> > like :
> > press 3 to go to 3rd buffer
> 
> no , That's a lot of keys to map

dont worry about it, it'll dynamically map and unmap itself

**Comment by max397574** [comment]
no you don't have to map them

**Comment by tomasky** [comment]
letters are easy to remember

**Comment by siduck** [comment]
> no you don't have to map them

hmm how do I know which key the user pressed in vim?

**Comment by max397574** [comment]
you can use `vim.fn.getchar()` to get input

**Comment by siduck** [comment]
> 

what does this do

**Comment by tomasky** [comment]
Changing to numbers is simple, and I think the two features can coexist

**Comment by tomasky** [comment]
The letter is convenient because you don't need to look at the location because it is the first letter of the file name

**Comment by siduck** [comment]
> Changing to numbers is simple, and I think the two features can coexist

i dont understand the code from akhinso so a bit hesitant to merge this :thinking:

**Comment by tomasky** [comment]
if i want to jump to file `init.lua` ,i just :TbufPick  and press i , dont need to look this file`s locatioin

**Comment by siduck** [comment]
> if i want to jump to file `init.lua` ,i just :TbufPick and press i , dont need to look this file`s location

true, makes sense

**Comment by siduck** [comment]
> > ok this works but we have to run tbufpick then the letter, wouldnt it be nice to just have numbers to switch buffers?
> > like :
> > press 3 to go to 3rd buffer
> 
> no , That's a lot of keys to map

example 

```lua
local bufnrs = { 1, 3, 9 } -- we store them in vim.t.bufs ( tab local table )

for index, _ in ipairs(bufnrs) do
  vim.keymap("n", index, function()
    vim.cmd("b" .. bufnrs[index])
  end)
end
```

**Comment by max397574** [comment]
you could also do what I did though
us getchar

**Comment by siduck** [comment]
> you could also do what I did though us getchar

seems more complex and would that code snippet run all the time?

**Comment by max397574** [comment]
wym with "all the time" ?

**Comment by siduck** [comment]
> wym with "all the time" ?

how would it know when I pressed the key?

**Comment by siduck** [comment]
> yes , like custom/init.lua and nvim/init.lua, you can switch to `tomasky/nvchad-ui` and see what it looks like

image

i was expecting it to use i to lspisntaller.lua file here :thinking:

**Comment by tomasky** [comment]
>what if i just want to press the key directly , like 1 2 etc
You can do that, you just have to display each file name with an buf id ,then map id to number key

**Comment by tomasky** [comment]
> i was expecting it to use i to lspisntaller.lua file here and a for alpha

oh, There might be a bug, i will check that

**Comment by siduck** [comment]
> > what if i just want to press the key directly , like 1 2 etc
> 
> You can do that, you just have to display each file name with an buf id ,then map id to number key ,but buf id is dynamic, so you still have to renumber each file name

dont worry about the id, we wont use that . I can easily use the index from vim.t.bufs and put it next to buffer name

**Comment by tomasky** [comment]
display name just like this:

**Comment by tomasky** [comment]
> i was expecting it to use i to lspisntaller.lua file here and a for alpha

   `lspisntaller.lua` and `lspconfig.lua` ，  Because they have the same initials ,cannot display the same letter

**Comment by siduck** [comment]
> display name just like this: 

oh that would work only on kitty ig, cuz all other terminals dont support multiple font sizes :thinking:

**Comment by siduck** [comment]
> > i was expecting it to use i to lspisntaller.lua file here and a for alpha
> 
> `lspinstaller.lua` and `lspconfig.lua` ， Because they have the same initials ,cannot display the same letter

we cant have this feature then, maybe only for numbers like + no need to map anything like : 

:TbufNumPick 3

**Comment by tomasky** [comment]
:TbufNumPick 3  , this needs to map keys, `getchar` doesn't need

**Comment by tomasky** [comment]
:TbufNumPick 3  , this needs to map keys, `getchar` doesn't need

**Comment by tomasky** [comment]
i can Implement it with number  and getchar ,but i hope to keep letter . Maybe we can make them configurable


mode = both ,number, letter

**Comment by siduck** [comment]
> :TbufNumPick 3 , this needs to map keys, `getchar` doesn't need

no it doesnt need to map keys, when we press TbufNumPkck then we need to all buffers will show their numbers then we need to press the number

**Comment by tomasky** [comment]
> > :TbufNumPick 3 , this needs to map keys, `getchar` doesn't need
> 
> no it doesnt need to map keys, when we press TbufNumPkck then we need to all buffers will show their numbers then we need to press the number

so ,that needs getchar

**Comment by siduck** [comment]
> > > :TbufNumPick 3 , this needs to map keys, `getchar` doesn't need
> > 
> > 
> > no it doesnt need to map keys, when we press TbufNumPkck then we need to all buffers will show their numbers then we need to press the number
> 
> so ,that needs getchar

yep and it will be 100% accurate than the letters stuff

**Comment by tomasky** [comment]
so ,you hope to remove letter or  just add a new command with number

**Comment by siduck** [comment]
> so ,you hope to remove letter or just add a new command with number

I want to add  both, but not now. and bufferline's way to generate characters for buffer picking isnt that accurate and it'll take time to perfect it. So first i'll fix existing nvchad issues then also make mappings lazyloadable then implement our own way to pick buffers, make an issue on this repo so I wont forget it

**Comment by tomasky** [comment]
it can't be precise if   use letters, Maybe I can just  implement numbers  first. And display parent dir name is helpful

**Comment by tomasky** [comment]
@siduck  I have implemented the number mode, you can check my  branch

**Pull request merged**
