### PR TITLE
Fix(tabufline): fixed incorrect buf validity check, fixed adding current buf to new tab 

### LINKED ISSUE #22: no name file always open whenever i open something from nerd tree
**Describe the bug**

**To Reproduce**
1. open any file
2. CTRL n and open a new file
3. now there are 3 things open , two files that i open , third imposter with name of `No Name`

**Expected behavior**
only two intended file open 
no No Name fuckery
**Screenshots**
Peek 2022-09-23 19-30

### PR DESCRIPTION
**Pull request by lll9p**
Combine `vim.api.nvim_buf_is_valid` with `vim.bo[bufnr].buflisted` to verify `buffer`.
Fix #22

### CODE REVIEW

**Comment by siduck** [comment]
btw vim.api.nvim_list_bufs() lists only buflisted buffers

**Comment by siduck** [comment]
@lll9p try vanilla nvchad ( no custom folder ) and check the issues!

**Comment by lll9p** [comment]
> @lll9p try vanilla nvchad ( no custom folder ) and check the issues!

I removed custom folder and packer_compiled and packer plugins' dir, with updated nvchad, issues still exists.

By the way, I'm using Windows 11, Neovim 0.8 .
The below is the images and video of reproducing the issue.

producing


some unwanted buf poped up

tabnew issue

**Comment by siduck** [comment]
@lll9p i dont see the nvimtree buffername here

image

**Comment by lll9p** [comment]
> @lll9p i dont see the nvimtree buffername here

@siduck Very strange, I reproduced the issue on Archlinux, with a fresh user and fresh nvchad clone.

Latest Archlinux, nvim 0.8 .

reproducing  on archlinux

**Comment by siduck** [comment]
@lll9p ok this happens only after packercompile

**Comment by lll9p** [comment]
@siduck yes it does.

**Comment by siduck** [comment]
does your PR fix this issue? 

- Go to any file 
- InsertMode -> write anything so cmp completion shows up
- Escape
- PackerCompile


there will be 2 no named tabs added into tabufline

image

**Comment by lll9p** [comment]
> does your PR fix this issue?
> 
>     * Go to any file
> 
>     * InsertMode -> write anything so cmp completion shows up
> 
>     * Escape
> 
>     * PackerCompile
> 
> 
> there will be 2 no named tabs added into tabufline
> 
> image

@siduck Yes my PR fixed it.

**Before**

before fixed

**After**

after fixed

**Comment by siduck** [comment]
@lll9p all good! just move the isBufValid function `tabufline/init.lua` file, all util related etc functions are there only

**Comment by lll9p** [comment]
@siduck thanks! I moved isBufValid function to tabufline/init.lua .

**Comment by lll9p** [comment]
@siduck I think it's time to merge this pull, I haven't encountered a bug in this time.

**Comment by siduck** [comment]
> @siduck I think it's time to merge this pull, I haven't encountered a bug in this time.

done

**Comment by siduck** [comment]
@lll9p i doubt if this is needed now, we're using lazy.nvim :grin:

**Pull request merged**
