### PR TITLE
refactor: concat the parent dir  when duplicate file names appear

### PR DESCRIPTION
**Pull request by tomasky**

### CODE REVIEW

**Comment by siduck** [comment]
ok first opened ~/.config/nvim/init.lua

image

then open `~/nvchad/lua/core/init.lua`
image

**Comment by tomasky** [comment]
but if this ,what is displayed?
~/a/k/b/init.lua
~/a/kc/init.lua

**Comment by tomasky** [comment]
or just check  whether the beginning is $HOME

**Comment by tomasky** [comment]
ok ,has a simple method to implement your request, wait a minute

**Comment by tomasky** [comment]
but you need to merge or close this pr ,otherwise it will conflict

**Comment by siduck** [comment]
> but if this ,what is displayed? `~/a/k/b/init.lua` `~/a/b/b/c/init.lua`
> 
> one is a forward search, and there's a backward search All of this feature can be done by this solution But some require sacrificing efficiency



> but if this ,what is displayed? `~/a/k/b/init.lua` `~/a/b/b/c/init.lua`
> 
> one is a forward search, and there's a backward search All of this feature can be done by this solution But some require sacrificing efficiency

oh that looks bad, i'll implement this feature myself

**Comment by siduck** [comment]
this looks complex so closing. 

https://github.com/NvChad/ui/commit/9d7fa2dd74d83df82e8b8ee1b1da27b98c327024

**Comment by tomasky** [comment]
The algorithm hasn't changed，There is no increase in efficiency

**Comment by siduck** [comment]
@tomasky the code will run only on bufadd/bufdelete/tabnew events tho, there's no affect on performance

**Comment by tomasky** [comment]
no ,tabuflinePrev and tabuflineNext　will call the function.

**Comment by siduck** [comment]
> no ,tabuflinePrev and tabuflineNext　will call the function.

yea and the bufferlist will barely go more than 10+ buffers so looping through them isnt that bad, but i'll think about something efficient today

**Pull request closed without merging**
