### PR TITLE
refactor(tbufpick): renumber the visible buffers when executing tbufpick

### PR DESCRIPTION
**Pull request by tomasky**

### CODE REVIEW

**Comment by tomasky** [comment]
test it with my branch

**Comment by siduck** [comment]
Can u show the behaviour of the tbufpick with / without this PR?

**Comment by siduck** [comment]
> you can test it with my branch , this pr also improves efficiency, It's the one I mentioned to you last time.

oh u mean 10+ buffers?

**Comment by tomasky** [comment]
yes,  because just numbers visiable buffers

**Pull request merged**
