### PR TITLE
Ignore copilot from statusline LSP

### LINKED ISSUE #241: Copilot shown as LSP in statusline
When Copilot is enabled then it's rendered as an LSP in the status line instead of the LSP.
It should be ignored similarly to `null-ls`.

Screenshot 2024-03-05 at 13 10 27

### PR DESCRIPTION
**Pull request by le4ker**
Closes #241

### CODE REVIEW

**Comment by lucario387** [comment]
I'd rather just drop the support for both :)
And tell people to override it like

```
local s = modules[some_pos]
modules[some_pos] = (function()
  return s:gsub("foo", "")
end)()
```

**Comment by le4ker** [comment]
> And tell people to override it like

Can you explain the snippet bellow? 

I agree that blacklisting one by one the LSPs that are not LSPs doesn't scale, but I didn't get how it can be done 😅

**Comment by siduck** [comment]
@le4ker currently the solution's a workaround. What if there will be more stuff like copilot null-ls etc, it'd be a pain to keep them in check. 

We should see what differs them   from normal lsps,  ask on r/neovim or check that client* parameter, vim.print it and see the differences if there are any   :thinking:

**Comment by lucario387** [comment]
> Can you explain the snippet bellow?

It removes all foo substrings from the result

**Comment by siduck** [comment]
> > Can you explain the snippet bellow?
> 
> It removes all foo substrings from the result

that'd be bad, he wants to show active lsp too. with your change it'll show nothing

**Comment by lucario387** [comment]
> that'd be bad, he wants to show active lsp too. with your change it'll show nothing

Don't you see you can use that to strip away null-lsp, copilot and such from the string?

**Comment by siduck** [comment]
> > that'd be bad, he wants to show active lsp too. with your change it'll show nothing
> 
> Don't you see you can use that to strip away null-lsp, copilot and such from the string?

yes but if the result is just null-ls then then your module will just hide it. If we were showing all attached lsps then that'd be different, but we show only the 1st lsp

**Comment by siduck** [comment]
https://github.com/NvChad/ui/issues/241#issuecomment-1981154870

**Pull request closed without merging**
