### PR TITLE
fix: unwanted space on filename.

### PR DESCRIPTION
**Pull request by Alexis12119**
Before:
first

After:
second

### CODE REVIEW

**Comment by siduck** [comment]
@Alexis12119 it looks bad with only default statusline theme tho, check it

**Comment by Alexis12119** [comment]
> @Alexis12119 it looks bad with only default statusline theme tho, check it

Oh, you're right. maybe we can just change the minimal one? Is that alright?

**Comment by Alexis12119** [comment]
It's fine if you don't want to. I'll respect your decision.

**Comment by siduck** [comment]
> > @Alexis12119 it looks bad with only default statusline theme tho, check it
> 
> Oh, you're right. maybe we can just change the minimal one? Is that alright?

no, this PR looks fine on all themes expect the default one so i'll change that

**Pull request merged**
