### PR TITLE
Fix :MasonInstallAll issue

### PR DESCRIPTION
**Pull request by alexandr-martirosyan**
Issue described [here](https://github.com/NvChad/ui/issues/305)

### CODE REVIEW

**Comment by siduck** [comment]
that data is optional and users must only use it if they want to install mason pkg which isnt configured by lspconfig, nvim-lint,  conform

**Comment by alexandr-martirosyan** [comment]
> that data is optional and users must only use it if they want to install mason pkg which isnt configured by lspconfig, nvim-lint, conform

Yes, but, the current implementation does not allow for installing packages such as "nomicfoundation-solidity-language-server" using the mason.opts.ensure_installed = { "nomicfoundation-solidity-language-server" } method, or any other package whose name differs in the Mason registry.

**Comment by siduck** [comment]
u sure? 
image
its named the same

**Comment by siduck** [comment]
you dont need to add that in ensure_installed if you're already using its lspconfig.setup call, the masoninstallall cmd will capture from there

**Comment by alexandr-martirosyan** [comment]
Yes, I’m aware of that. However, my current Neovim setup relies on the ensure_installed option in Mason.opts, which functioned correctly until the recent changes. Therefore, I need to continue using the ensure_installed field. Could you clarify if there has been an architectural change requiring us to use the values from [this link](https://github.com/NvChad/ui/blob/v2.5/lua/nvchad/mason/names.lua) instead of the actual names from the Mason registry?
For example, should I use `solidity_ls_nomicfoundation` instead of `nomicfoundation-solidity-language-server`, which worked previously?

**Comment by siduck** [comment]
`require("lspconfig").solidity_ls_nomicfoundation.setup()`

**Comment by siduck** [comment]
ah wait, i understand the issue now! you can try this one

image

**Comment by alexandr-martirosyan** [comment]
> ah wait, i understand the issue now! you can try this one

Should I update my pull request with the code you’ve provided?

**Comment by siduck** [comment]
yes

**Review by siduck — APPROVED** [review]

**Pull request merged**
