### PR TITLE
refactor: concat the parent dir  when duplicate file names appear

### PR DESCRIPTION
**Pull request by tomasky**

### CODE REVIEW

**Comment by siduck** [comment]
@tomasky why close it?

**Comment by tomasky** [comment]
now you can reopen it , Because many use cases need to be tested and fixed

**Comment by siduck** [comment]
> now you can reopen it , Because many use cases need to be tested and fixed

unable to reopen, 
image

**Comment by tomasky** [comment]
It feels like sometimes Github has issues, It has been resubmitted.

**Pull request closed without merging**
